version: 2
jobs:
  build:
    # Run cypress by docker?????
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
#      Check is cache exist or not if it is - run by cache
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
#      If no cache or cache update, this will install these dependencies.
      - run:
          name: Install Dependencies
          command: npm ci
#      save cache (save to new cache, all dependencies if no cache or just cache for new dependencies)
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run
      - store_artifacts:
          path: ~/repo/api-testing-with-cypress